language: haskell

env:
  matrix:
    - GHCVER=7.10.2 CABALVER=1.22
    - GHCVER=8.0.1 CABALVER=1.24
    - GHCVER=head CABALVER=head
  global:
    - UBUNTU_PKGS="libgtk-3-dev libcairo2-dev"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools"
    - HEAD_DEPS="active dual-tree monoid-extras diagrams-core diagrams-solve diagrams-lib  statestack diagrams-cairo diagrams-svg diagrams-postscript diagrams-rasterific diagrams-builder"


matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head

before_install:
  - |
    if [ $GHCVER = "7.10.1" ]; then
      echo "constraints:transformers installed, ghc installed" >> cabal.config
    else
      echo "constraints:ghc installed" >> cabal.config
    fi
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-haddock\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
